=== Dracks/recon-types/schema/unit.json
{
  "$id": "https://codename-recon.com/schema/unit.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Unit",
  "type": "object",
  "properties": {
    "name": { "type": "string", "pattern": "^([A-Z]|_)+$" },
    "health": { "type": "integer", "minimum": 0, "maximum": 100 },
    "movement_points": { "type": "integer", "minimum": 0 },
    "ammo": { "type": "integer", "minimum": -1 },
    "fuel": { "type": "integer", "minimum": 0 },
    "daily_fuel_decay": { "type": "integer", "minimum": 0 },
    "vision": { "type": "integer", "minimum": 0 },
    "min_range": { "type": "integer", "minimum": 0 },
    "max_range": { "type": "integer", "minimum": 0 },
    "movement_type": { "type": "integer" },
    "cost": { "type": "integer", "minimum": 0 },
    "can_capture": { "type": "boolean" },
    "can_move_and_attack": { "type": "boolean" },
    "can_hide": { "type": "boolean" },
    "can_dive": { "type": "boolean" },
    "weapons": { "type": "array", "items": { "$ref": "#/definitions/weapon" } },
    "damage_table": {
      "type": "object",
      "additionalProperties": { "type": "integer" }
    },
    "can_load": { "type": "boolean" },
    "carrying_types": { "type": ["null", "array"] },
    "carrying_size": { "type": "integer" },
    "description": { "type": "string" }
  },
  "required": [
    "name",
    "health",
    "movement_points",
    "ammo",
    "fuel",
    "daily_fuel_decay",
    "vision",
    "min_range",
    "max_range",
    "movement_type",
    "cost",
    "can_capture",
    "can_move_and_attack",
    "can_load",
    "weapons",
    "damage_table",
    "carrying_types",
    "carrying_size",
    "description"
  ],
  "definitions": {
    "weapon": {
      "enum": [
        "Artillery Cannon",
        "Bazooka",
        "Light Tank Cannon",
        "Machine Gun",
        "Medium Tank Cannon",
        "Rockets",
        "Tank Machine Gun",
        "Vulcan Cannon"
      ]
    }
  }
}

=== Dracks/recon-types/units/mech.json
{
  "name": "MECH",
  "health": 100,
  "movement_points": 2,
  "ammo": 3,
  "fuel": 70,
  "daily_fuel_decay": 0,
  "vision": 2,
  "min_range": 1,
  "max_range": 1,
  "movement_type": 7,
  "cost": 2500,
  "can_capture": true,
  "can_move_and_attack": true,
  "can_load": false,
  "weapons": ["Bazooka", "Machine Gun"],
  "damage_table": {
    "Artillery Cannon": 90,
    "Machine Gun": 55,
    "Rockets": 90,
    "Tank Machine Gun": 70,
    "Vulcan Cannon": 105
  },
  "carrying_types": [],
  "carrying_size": 0,
  "description": "MECH_DESCRIPTION"
}

=== Dracks/recon-types/units/apc.json
{
  "name": "APC",
  "health": 100,
  "movement_points": 6,
  "ammo": 0,
  "fuel": 70,
  "daily_fuel_decay": 0,
  "vision": 1,
  "min_range": 0,
  "max_range": 0,
  "movement_type": 1,
  "cost": 5000,
  "can_capture": false,
  "can_move_and_attack": false,
  "can_load": true,
  "weapons": [],
  "damage_table": {
    "Artillery Cannon": 70,
    "Bazooka": 75,
    "Light Tank Cannon": 75,
    "Machine Gun": 14,
    "Medium Tank Cannon": 95,
    "Rockets": 75,
    "Tank Machine Gun": 45,
    "Vulcan Cannon": 50
  },
  "carrying_types": [6, 7],
  "carrying_size": 1,
  "description": "APC_DESCRIPTION"
}

=== Dracks/recon-types/units/rocket.json
{
  "name": "ROCKET",
  "health": 100,
  "movement_points": 5,
  "ammo": 6,
  "fuel": 50,
  "daily_fuel_decay": 0,
  "vision": 1,
  "min_range": 3,
  "max_range": 5,
  "movement_type": 2,
  "cost": 15000,
  "can_capture": false,
  "can_move_and_attack": false,
  "can_load": false,
  "weapons": ["Rockets"],
  "damage_table": {
    "Artillery Cannon": 80,
    "Bazooka": 85,
    "Light Tank Cannon": 85,
    "Machine Gun": 25,
    "Medium Tank Cannon": 95,
    "Rockets": 75,
    "Tank Machine Gun": 55,
    "Vulcan Cannon": 55
  },
  "carrying_types": null,
  "carrying_size": 0,
  "description": "ROCKET_DESCRIPTION"
}

=== Dracks/recon-types/units/tank.json
{
  "name": "LIGHT_TANK",
  "health": 100,
  "movement_points": 6,
  "ammo": 9,
  "fuel": 70,
  "daily_fuel_decay": 0,
  "vision": 3,
  "min_range": 1,
  "max_range": 1,
  "movement_type": 1,
  "cost": 7000,
  "can_capture": false,
  "can_move_and_attack": true,
  "can_load": false,
  "weapons": ["Light Tank Cannon", "Tank Machine Gun"],
  "damage_table": {
    "Artillery Cannon": 70,
    "Bazooka": 55,
    "Light Tank Cannon": 55,
    "Machine Gun": 5,
    "Medium Tank Cannon": 85,
    "Rockets": 80,
    "Tank Machine Gun": 6,
    "Vulcan Cannon": 25
  },
  "carrying_types": null,
  "carrying_size": 0,
  "description": "LIGHT_TANK_DESCRIPTION"
}
